version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: e2e

  adminer:
    image: adminer
    ports:
      - 8080:8080